#!/bin/bash

echo "[+] Instalando dependencias para VolIQ-Analys..."

# Asegura que pip esté actualizado
echo "[+] Verificando pip..."
python3 -m pip install --upgrade --user pip

# Usamos pip del usuario por si es una versión más nueva
PIP_CMD="$HOME/.local/bin/pip"

if [ ! -f "$PIP_CMD" ]; then
    echo "[!] No se encontró pip actualizado en ~/.local/bin. Usando pip global."
    PIP_CMD="pip"
fi

echo "[+] Instalando paquetes requeridos..."
$PIP_CMD install yara-python iocextract pyyaml configparser

echo "[✓] Instalación de dependencias completada."
